[2023-06-08T21:14:26.705+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_v04.greet scheduled__2023-06-07T00:00:00+00:00 [queued]>
[2023-06-08T21:14:26.711+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_v04.greet scheduled__2023-06-07T00:00:00+00:00 [queued]>
[2023-06-08T21:14:26.712+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-08T21:14:26.719+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): greet> on 2023-06-07 00:00:00+00:00
[2023-06-08T21:14:26.722+0000] {standard_task_runner.py:57} INFO - Started process 3764 to run task
[2023-06-08T21:14:26.725+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_v04', 'greet', 'scheduled__2023-06-07T00:00:00+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_taskflow.py', '--cfg-path', '/tmp/tmpdublxng3']
[2023-06-08T21:14:26.727+0000] {standard_task_runner.py:85} INFO - Job 94: Subtask greet
[2023-06-08T21:14:26.760+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_taskflow_v04.greet scheduled__2023-06-07T00:00:00+00:00 [running]> on host e3f9b08eb2c7
[2023-06-08T21:14:26.793+0000] {abstractoperator.py:597} ERROR - Exception rendering Jinja template for task 'greet', field 'op_kwargs'. Template: {'first_name': XComArg(<Task(_PythonDecoratedOperator): get_name>, 'first_name'), 'last_name': XComArg(<Task(_PythonDecoratedOperator): get_name>, 'last_name'), 'age': XComArg(<Task(_PythonDecoratedOperator): get_age>)}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 158, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 373, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at dag_with_taskflow_v04 with key="first_name" is not found!
[2023-06-08T21:14:26.801+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 158, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 373, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at dag_with_taskflow_v04 with key="first_name" is not found!
[2023-06-08T21:14:26.804+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_taskflow_v04, task_id=greet, execution_date=20230607T000000, start_date=20230608T211426, end_date=20230608T211426
[2023-06-08T21:14:26.809+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 94 for task greet (XComArg result from get_name at dag_with_taskflow_v04 with key="first_name" is not found!; 3764)
[2023-06-08T21:14:26.817+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-08T21:14:26.829+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09T13:06:38.221+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_v04.greet scheduled__2023-06-07T00:00:00+00:00 [queued]>
[2023-06-09T13:06:38.226+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_v04.greet scheduled__2023-06-07T00:00:00+00:00 [queued]>
[2023-06-09T13:06:38.226+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-09T13:06:38.235+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): greet> on 2023-06-07 00:00:00+00:00
[2023-06-09T13:06:38.238+0000] {standard_task_runner.py:57} INFO - Started process 210 to run task
[2023-06-09T13:06:38.241+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_v04', 'greet', 'scheduled__2023-06-07T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_taskflow.py', '--cfg-path', '/tmp/tmppg57s5fp']
[2023-06-09T13:06:38.243+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask greet
[2023-06-09T13:06:38.280+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_taskflow_v04.greet scheduled__2023-06-07T00:00:00+00:00 [running]> on host e53046a1e8ac
[2023-06-09T13:06:38.354+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='znawawi' AIRFLOW_CTX_DAG_ID='dag_with_taskflow_v04' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2023-06-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-07T00:00:00+00:00'
[2023-06-09T13:06:38.355+0000] {logging_mixin.py:149} INFO - Hello world! My name is Jerry Fridman, and I am 19 years old!
[2023-06-09T13:06:38.355+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-06-09T13:06:38.362+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dag_with_taskflow_v04, task_id=greet, execution_date=20230607T000000, start_date=20230609T130638, end_date=20230609T130638
[2023-06-09T13:06:38.414+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-09T13:06:38.428+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
